// TODO: map-product-config?

// TODO COUNTERPARTY_ROLE_TYPES - invalid / misleading, codes, not strings
// TODO: "every rate", which field?

const COUNTERPARTY_ROLE_TYPES = {
  BROKER: 'BROKER',
  GUARANTOR: 'GUARANTOR',
};

const CREDIT_TYPES = {
  TERM: 'TERM',
  REVOLVER: 'REVOLVER',
};

const INSTRUMENT_TYPES = {
  CASH_ADVANCE: 'Cash Advance',
  INSURANCE: 'Insurance',
  GUARANTEE: 'Guarantee',
};

const PRODUCT_CONFIG_REQUIREMENT = {
  NOT_APPLICABLE: 'NOT_APPLICABLE',
  OPTIONAL: 'OPTIONAL',
  REQUIRED: 'REQUIRED',
};

export const PRODUCT_TYPES = {
  BIP: 'PRT001',
  EXIP: 'PRT002',
  BSS: 'PRT003',
  GEF: 'PRT004',
};

const REPAYMENT_TYPES = {
  BULLET: 'Bullet',
  SCHEDULED: 'Scheduled',
};

const PRODUCT_CONFIG_CORE = {
  BIP: {
    productType: PRODUCT_TYPES.BIP,
    name: 'Bond Insurance Product (BIP)',
    shortName: 'BIP',
    productActive: true,
    configuration: {
      commitmentDate: PRODUCT_CONFIG_REQUIREMENT.REQUIRED,
      issuedDate: PRODUCT_CONFIG_REQUIREMENT.REQUIRED,
      effectiveDate: PRODUCT_CONFIG_REQUIREMENT.REQUIRED,
      availabilityEndDate: PRODUCT_CONFIG_REQUIREMENT.REQUIRED,
      expiryDate: PRODUCT_CONFIG_REQUIREMENT.REQUIRED,
      creditType: CREDIT_TYPES.TERM,
      participations: PRODUCT_CONFIG_REQUIREMENT.REQUIRED,
      scheduledRepayments: PRODUCT_CONFIG_REQUIREMENT.REQUIRED,
      nonCashObligations: PRODUCT_CONFIG_REQUIREMENT.REQUIRED,
      cashObligations: PRODUCT_CONFIG_REQUIREMENT.REQUIRED,
      accrualSchedule: PRODUCT_CONFIG_REQUIREMENT.REQUIRED,
      pimOwner: PRODUCT_CONFIG_REQUIREMENT.REQUIRED,
      riskRating: PRODUCT_CONFIG_REQUIREMENT.REQUIRED,
      preCreditPeriod: PRODUCT_CONFIG_REQUIREMENT.REQUIRED,
      creditPeriod: PRODUCT_CONFIG_REQUIREMENT.REQUIRED,
      lossGivenDefault: PRODUCT_CONFIG_REQUIREMENT.REQUIRED,
      provisionRate: PRODUCT_CONFIG_REQUIREMENT.REQUIRED,
      forecastYear: PRODUCT_CONFIG_REQUIREMENT.NOT_APPLICABLE,
      bankRate: PRODUCT_CONFIG_REQUIREMENT.OPTIONAL,
      instrumentType: INSTRUMENT_TYPES.INSURANCE,
      repaymentType: REPAYMENT_TYPES.BULLET,
      fees: {
        creation: PRODUCT_CONFIG_REQUIREMENT.REQUIRED,
        inLife: PRODUCT_CONFIG_REQUIREMENT.OPTIONAL,
      },
      obligations: {
        creation: PRODUCT_CONFIG_REQUIREMENT.REQUIRED,
        inLife: PRODUCT_CONFIG_REQUIREMENT.OPTIONAL,
      },
      reinsurance: {
        creation: PRODUCT_CONFIG_REQUIREMENT.OPTIONAL,
        inLife: PRODUCT_CONFIG_REQUIREMENT.OPTIONAL,
      },
      leadDays: {
        repayments: 1,
        interestAccruals: 2,
        accruingFees: 3,
      },
    },
    additionalRates: ['ARTOTH'],
    accrualSchedules: [
      {
        code: 'PAC01',
        cashIndicator: true,
      },
    ],
    baseRates: ['BRTOTH'],
    counterpartyRoleTypes: [COUNTERPARTY_ROLE_TYPES.BROKER],
    facilityCategoryTypes: ['FCT001', 'FCT002'],
    feeTypes: ['BEX', 'PLA'],
    obligationSubtypes: ['OST001', 'OST002', 'OST003'],
    additionalRateTypes: [],
    baseRateTypes: [],
    accrualScheduleTypes: [],
    account: ['1', '2', '3'],
  },
  EXIP: {
    productType: PRODUCT_TYPES.EXIP,
    name: 'Export Insurance Product (EXIP)',
    shortName: 'EXIP',
    productActive: true,
    configuration: {
      commitmentDate: PRODUCT_CONFIG_REQUIREMENT.REQUIRED,
      issuedDate: PRODUCT_CONFIG_REQUIREMENT.NOT_APPLICABLE,
      effectiveDate: PRODUCT_CONFIG_REQUIREMENT.OPTIONAL,
    },
    counterpartyRoleTypes: [COUNTERPARTY_ROLE_TYPES.BROKER, COUNTERPARTY_ROLE_TYPES.GUARANTOR],
    facilityCategoryTypes: ['FCT001', 'FCT002'],
    feeTypes: ['BEX', 'PLA'],
    obligationSubtypes: ['OST001', 'OST002', 'OST003'],
    account: ['1', '2', '3'],
  },
};

const TEMPORARY_EXAMPLES = {
  ALL_REQUIRED_INSURANCE: {
    productType: 'ALL_REQUIRED_INSURANCE',
    name: 'Insurance product with all fields required',
    shortName: 'ALL_REQUIRED_INSURANCE',
    productActive: true,
    configuration: {
      signedDate: PRODUCT_CONFIG_REQUIREMENT.REQUIRED,
      commitmentDate: PRODUCT_CONFIG_REQUIREMENT.REQUIRED,
      issuedDate: PRODUCT_CONFIG_REQUIREMENT.REQUIRED,
      effectiveDate: PRODUCT_CONFIG_REQUIREMENT.REQUIRED,
      availabilityEndDate: PRODUCT_CONFIG_REQUIREMENT.REQUIRED,
      expiryDate: PRODUCT_CONFIG_REQUIREMENT.REQUIRED,
      creditType: CREDIT_TYPES.TERM,
      participations: PRODUCT_CONFIG_REQUIREMENT.REQUIRED,
      scheduledRepayments: PRODUCT_CONFIG_REQUIREMENT.REQUIRED,
      nonCashObligations: PRODUCT_CONFIG_REQUIREMENT.REQUIRED,
      cashObligations: PRODUCT_CONFIG_REQUIREMENT.REQUIRED,
      accrualSchedule: PRODUCT_CONFIG_REQUIREMENT.REQUIRED,
      pimOwner: PRODUCT_CONFIG_REQUIREMENT.REQUIRED,
      riskRating: PRODUCT_CONFIG_REQUIREMENT.REQUIRED,
      preCreditPeriod: PRODUCT_CONFIG_REQUIREMENT.REQUIRED,
      creditPeriod: PRODUCT_CONFIG_REQUIREMENT.REQUIRED,
      lossGivenDefault: PRODUCT_CONFIG_REQUIREMENT.REQUIRED,
      provisionRate: PRODUCT_CONFIG_REQUIREMENT.REQUIRED,
      forecastYear: PRODUCT_CONFIG_REQUIREMENT.NOT_APPLICABLE,
      bankRate: PRODUCT_CONFIG_REQUIREMENT.OPTIONAL,
      instrumentType: INSTRUMENT_TYPES.INSURANCE,
      repaymentType: REPAYMENT_TYPES.BULLET,
      fees: {
        creation: PRODUCT_CONFIG_REQUIREMENT.REQUIRED,
        inLife: PRODUCT_CONFIG_REQUIREMENT.REQUIRED,
      },
      obligations: {
        creation: PRODUCT_CONFIG_REQUIREMENT.REQUIRED,
        inLife: PRODUCT_CONFIG_REQUIREMENT.REQUIRED,
      },
      reinsurance: {
        creation: PRODUCT_CONFIG_REQUIREMENT.OPTIONAL,
        inLife: PRODUCT_CONFIG_REQUIREMENT.OPTIONAL,
      },
      leadDays: {
        repayments: 5,
        interestAccruals: 2,
        accruingFees: 1,
      },
    },
    additionalRates: ['ARTOTH'],
    accrualSchedules: [
      {
        code: 'PAC01',
        cashIndicator: true,
      },
      {
        code: 'CTL01',
        cashIndicator: true,
      },
      {
        code: 'CTL02',
        cashIndicator: false,
      },
      {
        code: 'CTL03',
        cashIndicator: false,
      },
      {
        code: 'PEN01',
        cashIndicator: true,
      },
    ],
    baseRates: ['BRTOTH'],
    counterpartyRoleTypes: ['CRT001', 'CRT002', 'CRT004', 'CRT005', 'CRT006', 'CRT013', 'CRT014', 'CRT018', 'CRT036', 'CRT040', 'CRT042', 'CRT043', 'CRT045'],
    facilityCategoryTypes: ['FCT001', 'FCT002', 'FCT003', 'FCT004', 'FCT005', 'FCT006', 'FCT007'],
    feeTypes: ['BEX', 'PLA', 'CMF', 'SUP'],
    obligationSubtypes: [
      'OST001',
      'OST002',
      'OST003',
      'OST004',
      'OST005',
      'OST006',
      'OST008',
      'OST009',
      'OST010',
      'OST011',
      'OST012',
      'OST013',
      'OST014',
      'OST015',
      'OST016',
      'OST017',
      'OST018',
      'OST019',
      'OST020',
      'OST021',
      'OST022',
      'OST023',
      'OST025',
      'OST026',
    ],
    additionalRateTypes: [],
    baseRateTypes: [],
    accrualScheduleTypes: [],
    account: ['1', '2', '3'],
  },
  ALL_REQUIRED_GUARANTEE: {
    productType: 'ALL_REQUIRED_GUARANTEE',
    name: 'Guarantee product with all fields required',
    shortName: 'ALL_REQUIRED_GUARANTEE',
    productActive: true,
    configuration: {
      signedDate: PRODUCT_CONFIG_REQUIREMENT.REQUIRED,
      commitmentDate: PRODUCT_CONFIG_REQUIREMENT.REQUIRED,
      issuedDate: PRODUCT_CONFIG_REQUIREMENT.REQUIRED,
      effectiveDate: PRODUCT_CONFIG_REQUIREMENT.REQUIRED,
      availabilityEndDate: PRODUCT_CONFIG_REQUIREMENT.REQUIRED,
      expiryDate: PRODUCT_CONFIG_REQUIREMENT.REQUIRED,
      creditType: CREDIT_TYPES.TERM,
      participations: PRODUCT_CONFIG_REQUIREMENT.REQUIRED,
      scheduledRepayments: PRODUCT_CONFIG_REQUIREMENT.REQUIRED,
      nonCashObligations: PRODUCT_CONFIG_REQUIREMENT.REQUIRED,
      cashObligations: PRODUCT_CONFIG_REQUIREMENT.REQUIRED,
      accrualSchedule: PRODUCT_CONFIG_REQUIREMENT.REQUIRED,
      pimOwner: PRODUCT_CONFIG_REQUIREMENT.REQUIRED,
      riskRating: PRODUCT_CONFIG_REQUIREMENT.REQUIRED,
      preCreditPeriod: PRODUCT_CONFIG_REQUIREMENT.REQUIRED,
      creditPeriod: PRODUCT_CONFIG_REQUIREMENT.REQUIRED,
      lossGivenDefault: PRODUCT_CONFIG_REQUIREMENT.REQUIRED,
      provisionRate: PRODUCT_CONFIG_REQUIREMENT.REQUIRED,
      forecastYear: PRODUCT_CONFIG_REQUIREMENT.NOT_APPLICABLE,
      bankRate: PRODUCT_CONFIG_REQUIREMENT.OPTIONAL,
      instrumentType: INSTRUMENT_TYPES.GUARANTEE,
      repaymentType: REPAYMENT_TYPES.BULLET,
      fees: {
        creation: PRODUCT_CONFIG_REQUIREMENT.REQUIRED,
        inLife: PRODUCT_CONFIG_REQUIREMENT.OPTIONAL,
      },
      obligations: {
        creation: PRODUCT_CONFIG_REQUIREMENT.REQUIRED,
        inLife: PRODUCT_CONFIG_REQUIREMENT.REQUIRED,
      },
      reinsurance: {
        creation: PRODUCT_CONFIG_REQUIREMENT.OPTIONAL,
        inLife: PRODUCT_CONFIG_REQUIREMENT.OPTIONAL,
      },
      leadDays: {
        repayments: 5,
        interestAccruals: 5,
        accruingFees: 1,
      },
    },
    additionalRates: ['ARTOTH', 'ARTCAS', 'ARTOTH', 'ARTPEN', 'ARTRAC'],
    accrualSchedules: [
      {
        code: 'PAC01',
        cashIndicator: true,
      },
      {
        code: 'CTL01',
        cashIndicator: true,
      },
      {
        code: 'CTL02',
        cashIndicator: false,
      },
      {
        code: 'CTL03',
        cashIndicator: false,
      },
      {
        code: 'PEN01',
        cashIndicator: true,
      },
    ],
    baseRates: ['BRTOTH', 'BRTINDX', 'BRTCIRR', 'BRTNLF'],
    counterpartyRoleTypes: ['CRT001', 'CRT002', 'CRT004', 'CRT005', 'CRT006', 'CRT013', 'CRT014', 'CRT018', 'CRT036', 'CRT040', 'CRT042', 'CRT043', 'CRT045'],
    facilityCategoryTypes: ['FCT001', 'FCT002', 'FCT003', 'FCT004', 'FCT005', 'FCT006', 'FCT007'],
    feeTypes: ['BEX', 'PLA', 'CMF', 'SUP'],
    obligationSubtypes: [
      'OST001',
      'OST002',
      'OST003',
      'OST004',
      'OST005',
      'OST006',
      'OST008',
      'OST009',
      'OST010',
      'OST011',
      'OST012',
      'OST013',
      'OST014',
      'OST015',
      'OST016',
      'OST017',
      'OST018',
      'OST019',
      'OST020',
      'OST021',
      'OST022',
      'OST023',
      'OST025',
      'OST026',
    ],
    baseRateTypes: [],
    accrualScheduleTypes: [],
    account: ['1', '2', '3'],
  },
  ALL_DISABLED: {
    productType: 'ALL_DISABLED',
    name: 'Product with minimal features',
    shortName: 'ALL_DISABLED',
    productActive: true,
    configuration: {
      signedDate: PRODUCT_CONFIG_REQUIREMENT.NOT_APPLICABLE,
      commitmentDate: PRODUCT_CONFIG_REQUIREMENT.NOT_APPLICABLE,
      issuedDate: PRODUCT_CONFIG_REQUIREMENT.NOT_APPLICABLE,
      effectiveDate: PRODUCT_CONFIG_REQUIREMENT.NOT_APPLICABLE,
      availabilityEndDate: PRODUCT_CONFIG_REQUIREMENT.NOT_APPLICABLE,
      expiryDate: PRODUCT_CONFIG_REQUIREMENT.NOT_APPLICABLE,
      creditType: CREDIT_TYPES.REVOLVER,
      participations: PRODUCT_CONFIG_REQUIREMENT.NOT_APPLICABLE,
      scheduledRepayments: PRODUCT_CONFIG_REQUIREMENT.NOT_APPLICABLE,
      nonCashObligations: PRODUCT_CONFIG_REQUIREMENT.NOT_APPLICABLE,
      cashObligations: PRODUCT_CONFIG_REQUIREMENT.NOT_APPLICABLE,
      accrualSchedule: PRODUCT_CONFIG_REQUIREMENT.NOT_APPLICABLE,
      pimOwner: PRODUCT_CONFIG_REQUIREMENT.NOT_APPLICABLE,
      riskRating: PRODUCT_CONFIG_REQUIREMENT.NOT_APPLICABLE,
      preCreditPeriod: PRODUCT_CONFIG_REQUIREMENT.NOT_APPLICABLE,
      creditPeriod: PRODUCT_CONFIG_REQUIREMENT.NOT_APPLICABLE,
      lossGivenDefault: PRODUCT_CONFIG_REQUIREMENT.NOT_APPLICABLE,
      provisionRate: PRODUCT_CONFIG_REQUIREMENT.NOT_APPLICABLE,
      forecastYear: PRODUCT_CONFIG_REQUIREMENT.NOT_APPLICABLE,
      bankRate: PRODUCT_CONFIG_REQUIREMENT.NOT_APPLICABLE,
      instrumentType: INSTRUMENT_TYPES.GUARANTEE,
      repaymentType: REPAYMENT_TYPES.BULLET,
      fees: {
        creation: PRODUCT_CONFIG_REQUIREMENT.NOT_APPLICABLE,
        inLife: PRODUCT_CONFIG_REQUIREMENT.NOT_APPLICABLE,
      },
      obligations: {
        creation: PRODUCT_CONFIG_REQUIREMENT.NOT_APPLICABLE,
        inLife: PRODUCT_CONFIG_REQUIREMENT.NOT_APPLICABLE,
      },
      reinsurance: {
        creation: PRODUCT_CONFIG_REQUIREMENT.NOT_APPLICABLE,
        inLife: PRODUCT_CONFIG_REQUIREMENT.NOT_APPLICABLE,
      },
      leadDays: {
        repayments: 5,
        interestAccruals: 5,
        accruingFees: 1,
      },
    },
    additionalRates: ['ARTOTH'],
    accrualSchedules: [
      {
        code: 'PAC01',
        cashIndicator: true,
      },
    ],
    baseRates: ['BRTOTH'],
    counterpartyRoleTypes: [COUNTERPARTY_ROLE_TYPES.BROKER],
    facilityCategoryTypes: ['FCT001', 'FCT002'],
    feeTypes: ['BEX', 'PLA'],
    obligationSubtypes: ['OST001', 'OST002', 'OST003'],
    additionalRateTypes: [],
    baseRateTypes: [],
    accrualScheduleTypes: [],
    account: ['1', '2', '3'],
  },
};

export const PRODUCT_CONFIG = {
  ...PRODUCT_CONFIG_CORE,
  ...TEMPORARY_EXAMPLES,
};
