import { DOM_BUSINESS_CENTRES, DomBusinessCentre } from './dom.constant';

const ODS_BUSINESS_CENTRE_CODES = [
  'AcB',
  'IvB',
  'AqB',
  'AaB',
  'AmB',
  'CGG',
  'CmB',
  'DxB',
  'DoB',
  'DbB',
  'FrB',
  'IrB',
  'IsB',
  'JoB',
  'KpB',
  'KwB',
  'LeB',
  'LoB',
  'LnB',
  'LdB',
  'LkB',
  'MdB',
  'MoB',
  'MpB',
  'MuB',
  'McB',
  'NYB',
  'PaB',
  'CzB',
  'SeB',
  'SiB',
  'StB',
  'TpB',
  'Tgt',
  'TkB',
  'VaB',
  'ViB',
  'WaB',
  'YnB',
] as const;

/**
 * Generate a dynamic object of ODS business centres.
 * @returns {Object}
 * @example
 * ```ts
 * {
 *   'A': 'A',
 *   'B': 'B',
 *   'C': 'C',
 * }
 * ```
 */
export const ODS_BUSINESS_CENTRES = Object.fromEntries(ODS_BUSINESS_CENTRE_CODES.map((name) => [name, name])) as {
  [CentreName in (typeof ODS_BUSINESS_CENTRE_CODES)[number]]: CentreName;
};

/**
 * Generate a union type of ODS business centre codes, e.g
 * 'A' | 'B' | 'C'
 */
type ODSBusinessCentreCode = (typeof ODS_BUSINESS_CENTRE_CODES)[number];

/**
 * List of all ODS business centre codes, mapped to DOM.
 * This allows us to map ODS business centres data, into DOM business centre codes.
 */
export const ODS_TO_DOM_BUSINESS_CENTRES_MAPPING: Record<ODSBusinessCentreCode, DomBusinessCentre> = {
  [ODS_BUSINESS_CENTRES.AcB]: DOM_BUSINESS_CENTRES.GH_ACC,
  [ODS_BUSINESS_CENTRES.IvB]: DOM_BUSINESS_CENTRES.CI_ABJ,
  [ODS_BUSINESS_CENTRES.AqB]: DOM_BUSINESS_CENTRES.ET_ADD,
  [ODS_BUSINESS_CENTRES.AaB]: DOM_BUSINESS_CENTRES.JO_AMM,
  [ODS_BUSINESS_CENTRES.AmB]: DOM_BUSINESS_CENTRES.NL_AMS,
  [ODS_BUSINESS_CENTRES.CGG]: DOM_BUSINESS_CENTRES.US_CHI,
  [ODS_BUSINESS_CENTRES.CmB]: DOM_BUSINESS_CENTRES.LK_CMB,
  [ODS_BUSINESS_CENTRES.DxB]: DOM_BUSINESS_CENTRES.SN_DKR,
  [ODS_BUSINESS_CENTRES.DoB]: DOM_BUSINESS_CENTRES.QA_DOH,
  [ODS_BUSINESS_CENTRES.DbB]: DOM_BUSINESS_CENTRES.AE_DXB,
  [ODS_BUSINESS_CENTRES.IrB]: DOM_BUSINESS_CENTRES.IQ_EBL,
  [ODS_BUSINESS_CENTRES.FrB]: DOM_BUSINESS_CENTRES.DE_FRA,
  [ODS_BUSINESS_CENTRES.IsB]: DOM_BUSINESS_CENTRES.TR_IST,
  [ODS_BUSINESS_CENTRES.JoB]: DOM_BUSINESS_CENTRES.ZA_JNB,
  [ODS_BUSINESS_CENTRES.KpB]: DOM_BUSINESS_CENTRES.UG_KLA,
  [ODS_BUSINESS_CENTRES.KwB]: DOM_BUSINESS_CENTRES.VC_KTN,
  [ODS_BUSINESS_CENTRES.LeB]: DOM_BUSINESS_CENTRES.GA_LBV,
  [ODS_BUSINESS_CENTRES.LoB]: DOM_BUSINESS_CENTRES.TG_LFW,
  [ODS_BUSINESS_CENTRES.LnB]: DOM_BUSINESS_CENTRES.GB_LON,
  [ODS_BUSINESS_CENTRES.LdB]: DOM_BUSINESS_CENTRES.AO_LAD,
  [ODS_BUSINESS_CENTRES.LkB]: DOM_BUSINESS_CENTRES.ZM_LUN,
  [ODS_BUSINESS_CENTRES.MdB]: DOM_BUSINESS_CENTRES.ES_MAD,
  [ODS_BUSINESS_CENTRES.MpB]: DOM_BUSINESS_CENTRES.MZ_MPM,
  [ODS_BUSINESS_CENTRES.MuB]: DOM_BUSINESS_CENTRES.DE_MUC,
  [ODS_BUSINESS_CENTRES.McB]: DOM_BUSINESS_CENTRES.OM_MCT,
  [ODS_BUSINESS_CENTRES.NYB]: DOM_BUSINESS_CENTRES.US_NYC,
  [ODS_BUSINESS_CENTRES.PaB]: DOM_BUSINESS_CENTRES.FR_PAR,
  [ODS_BUSINESS_CENTRES.CzB]: DOM_BUSINESS_CENTRES.BJ_PTN,
  [ODS_BUSINESS_CENTRES.MoB]: DOM_BUSINESS_CENTRES.CA_MTR,
  [ODS_BUSINESS_CENTRES.SeB]: DOM_BUSINESS_CENTRES.KR_SEL,
  [ODS_BUSINESS_CENTRES.SiB]: DOM_BUSINESS_CENTRES.SG_SIN,
  [ODS_BUSINESS_CENTRES.StB]: DOM_BUSINESS_CENTRES.SE_STO,
  [ODS_BUSINESS_CENTRES.TpB]: DOM_BUSINESS_CENTRES.TW_TPE,
  [ODS_BUSINESS_CENTRES.Tgt]: DOM_BUSINESS_CENTRES.TARGET,
  [ODS_BUSINESS_CENTRES.TkB]: DOM_BUSINESS_CENTRES.JP_TYO,
  [ODS_BUSINESS_CENTRES.VaB]: DOM_BUSINESS_CENTRES.CA_VAN,
  [ODS_BUSINESS_CENTRES.ViB]: DOM_BUSINESS_CENTRES.AT_VIE,
  [ODS_BUSINESS_CENTRES.WaB]: DOM_BUSINESS_CENTRES.PL_WAW,
  [ODS_BUSINESS_CENTRES.YnB]: DOM_BUSINESS_CENTRES.CM_YAO,
};
