export enum CustomerSubtypesEnum {
  ALTERNATIVE_FINANCE_PROVIDER = 'Alternative Finance Provider',
  BANK = 'Bank',
  BROKER = 'Broker',
  CHAMBER_OF_COMMERCE = 'Chamber of Commerce',
  CONSOLIDATED_JOINT_VENTURE = 'Consolidated Joint Venture',
  COOPERATIVE = 'Cooperative',
  CORPORATE_SYNDICATE = 'Corporate Syndicate',
  FOREIGN_CORPORATE = 'Foreign Corporate',
  FOREIGN_NON_CORPORATE = 'Foreign Non Corporate',
  INCORPORATED_CHARITY = 'Incorporated Charity',
  INSURANCE_COMPANY = 'Insurance Company',
  LIMITED = 'Limited',
  LIMITED_LIABILITY_PARTNERSHIP = 'Limited Liability Partnership',
  MEMBERSHIP_ORGANISATION = 'Membership Organisation',
  NA = 'N/A',
  NON_CORPORATE_SYNDICATE = 'Non Corporate Syndicate (where the Syndicate is a legal entity)',
  NON_INCORPORATED_CHARITY = 'Non Incorporated Charity',
  PARTNERSHIP = 'Partnership',
  PLC = 'PLC',
  PROFESSIONAL = 'Professional',
  SOLE_TRADER = 'Sole Trader',
  SPECIAL_PURPOSE = 'Special Purpose',
  TRADE_ASSOCIATION = 'Trade Association',
}
