import { RandomValueGenerator } from '@ukef-test/support/generator/random-value-generator';

const valueGenerator = new RandomValueGenerator();

export const ENVIRONMENT_VARIABLES = Object.freeze({
  NODE_ENV: 'test',
  LOG_LEVEL: 'debug',
  REDACT_LOGS: false,
  SINGLE_LINE_LOG_FORMAT: true,

  SWAGGER_USER: valueGenerator.string(),
  SWAGGER_PASSWORD: valueGenerator.string(),

  SF_CLIENT_ID: valueGenerator.word(),
  SF_CLIENT_SECRET: valueGenerator.word(),
  SF_INSTANCE_URL: valueGenerator.httpsUrl(),
  SF_USERNAME: valueGenerator.word(),
  SF_PASSWORD: valueGenerator.word(),
  SF_ACCESS_URL: valueGenerator.httpsUrl(),
  SF_MAX_REDIRECTS: 0,
  SF_TIMEOUT: 1000,

  ORDNANCE_SURVEY_URL: valueGenerator.httpsUrl(),
  ORDNANCE_SURVEY_KEY: valueGenerator.word(),

  ORDNANCE_SURVEY_MAX_REDIRECTS: 0,
  ORDNANCE_SURVEY_TIMEOUT: 5000,

  COMPANIES_HOUSE_URL: valueGenerator.httpsUrl(),
  COMPANIES_HOUSE_KEY: valueGenerator.word(),

  COMPANIES_HOUSE_MAX_REDIRECTS: 0,
  COMPANIES_HOUSE_TIMEOUT: 5000,

  API_KEY: valueGenerator.string(),
});

export const getEnvironmentVariablesForProcessEnv = (): NodeJS.ProcessEnv => ({
  ...ENVIRONMENT_VARIABLES,
  REDACT_LOGS: ENVIRONMENT_VARIABLES.REDACT_LOGS.toString(),
  SINGLE_LINE_LOG_FORMAT: ENVIRONMENT_VARIABLES.SINGLE_LINE_LOG_FORMAT.toString(),
  SF_MAX_REDIRECTS: ENVIRONMENT_VARIABLES.SF_MAX_REDIRECTS.toString(),
  SF_TIMEOUT: ENVIRONMENT_VARIABLES.SF_TIMEOUT.toString(),
  ORDNANCE_SURVEY_MAX_REDIRECTS: ENVIRONMENT_VARIABLES.ORDNANCE_SURVEY_MAX_REDIRECTS.toString(),
  ORDNANCE_SURVEY_TIMEOUT: ENVIRONMENT_VARIABLES.ORDNANCE_SURVEY_TIMEOUT.toString(),
  COMPANIES_HOUSE_MAX_REDIRECTS: ENVIRONMENT_VARIABLES.COMPANIES_HOUSE_MAX_REDIRECTS.toString(),
  COMPANIES_HOUSE_TIMEOUT: ENVIRONMENT_VARIABLES.COMPANIES_HOUSE_TIMEOUT.toString(),
});

export const TIME_EXCEEDING_ORDNANCE_SURVEY_TIMEOUT = ENVIRONMENT_VARIABLES.ORDNANCE_SURVEY_TIMEOUT + 500;
export const TIME_EXCEEDING_COMPANIES_HOUSE_TIMEOUT = ENVIRONMENT_VARIABLES.ORDNANCE_SURVEY_TIMEOUT + 500;
