name: Automated release

on:
  push:
    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Release a new version 🚀
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: uk-export-finance/mdm-api
          changelog-types: '[
              { "type": "feat", "section": "Features", "hidden": false},
              { "type": "fix", "section": "Bug Fixes", "hidden": false},
              { "type": "chore", "section": "Miscellaneous", "hidden": false},
              { "type": "docs", "section": "Documentation", "hidden": false}
            ]'
          extra-files: |
            README.md
            CHANGELOG.md
